# Sentinel values for local builds — obvious at a glance these didnt come from CI
set(SENTINEL_SHA    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")
set(SENTINEL_BRANCH "LOCAL")
set(SENTINEL_BUILD  "9999")

# --- GIT SHA ---
if(DEFINED ENV{GITHUB_SHA})
  set(GIT_SHA "$ENV{GITHUB_SHA}")
  message(STATUS "BuildInfo: SHA = ${GIT_SHA}")
else()
  set(GIT_SHA "${SENTINEL_SHA}")
  message(STATUS "BuildInfo: Not in CI — using sentinel SHA")
endif()

# --- BRANCH ---
if(DEFINED ENV{GITHUB_REF_NAME})
  set(GIT_BRANCH "$ENV{GITHUB_REF_NAME}")
  message(STATUS "BuildInfo: Branch = ${GIT_BRANCH}")
else()
  set(GIT_BRANCH "${SENTINEL_BRANCH}")
  message(STATUS "BuildInfo: Not in CI — using sentinel branch")
endif()

# --- BUILD NUMBER ---
if(DEFINED ENV{BUILD_NUMBER})
  set(BUILD_NUMBER "$ENV{BUILD_NUMBER}")
  message(STATUS "BuildInfo: Build number = ${BUILD_NUMBER}")
else()
  set(BUILD_NUMBER "${SENTINEL_BUILD}")
  message(STATUS "BuildInfo: Not in CI — using sentinel build number")
endif()

# --- Generate version.h ---
file(WRITE "${CMAKE_SOURCE_DIR}/inc/version.h"
"/* AUTO-GENERATED BY cmake/pre_build.cmake — DO NOT EDIT */
#ifndef VERSION_H
#define VERSION_H

#define GIT_SHA      \"${GIT_SHA}\"
#define GIT_BRANCH   \"${GIT_BRANCH}\"
#define BUILD_NUMBER \"${BUILD_NUMBER}\"

#endif /* VERSION_H */
")
message(STATUS "BuildInfo: Generated version.h -> ${CMAKE_SOURCE_DIR}/inc/version.h")